apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ducanh812/example-app
  newName: ducanh812/example-app
  newTag: b528149876e4eafc44ba8f6fa98d0fbc16da16c3
