apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ducanh812/example-app
  newName: ducanh812/example-app
  newTag: 93be1ad9053840d9c6e4e3a46ab5ef9ce7c9a42c
