apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ducanh812/example-app
  newName: ducanh812/example-app
  newTag: d340d9bdff5373331487bd810b5400f0611c4ef9
